# Generated by Django 5.1.5 on 2025-01-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.UUIDField()),
                ('character_class', models.UUIDField()),
                ('character_class_skill_choices', models.JSONField(default=list)),
                ('character_class_cantrip_choices', models.JSONField(blank=True, default=list)),
                ('character_class_spell_choices', models.JSONField(blank=True, default=list)),
                ('ability_points', models.JSONField(default=list)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=500)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('ideals', models.JSONField(blank=True, default=list)),
                ('bonds', models.JSONField(blank=True, default=list)),
                ('flaws', models.JSONField(blank=True, default=list)),
                ('height', models.CharField(max_length=100)),
                ('build', models.CharField(max_length=100)),
                ('skin_tone', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=100)),
                ('hair_style', models.CharField(max_length=100)),
                ('hair_length', models.CharField(max_length=100)),
                ('hair_type', models.CharField(max_length=100)),
                ('facial_hair_style', models.CharField(max_length=100)),
                ('facial_hair_length', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('eye_shape', models.CharField(max_length=100)),
                ('distinguishing_features', models.JSONField(blank=True, default=list)),
                ('clothing_style', models.CharField(max_length=200)),
                ('clothing_colors', models.JSONField(blank=True, default=list)),
                ('clothing_accessories', models.JSONField(blank=True, default=list)),
                ('liked_by', models.ManyToManyField(related_name='liked_characters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
