# Generated by Django 5.1.5 on 2025-02-10 12:57

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.UUIDField(choices=[(uuid.UUID('095914ea-d0a5-41dd-a003-6b5d4558a3ad'), 'Dwarf'), (uuid.UUID('576c1e3a-8464-4c1a-bbe7-3dde6813bbd3'), 'Elf'), (uuid.UUID('bf3b0c49-80cc-4258-85a0-3974f656469a'), 'Halfling'), (uuid.UUID('4725316c-cfc5-44a2-a69f-563088dec352'), 'Human'), (uuid.UUID('ec1f0336-fb41-4ac8-b1f3-2a574ddb1bd5'), 'Half-Elf'), (uuid.UUID('8b5c75dd-3d4f-41b4-a7c2-ec516f02256e'), 'Tiefling')])),
                ('character_class', models.UUIDField(choices=[(uuid.UUID('44f84547-8935-4ab4-bd29-fb60d0000d04'), 'Barbarian'), (uuid.UUID('ea6fbdc2-82c7-44d7-b065-bd70e136ccc7'), 'Bard'), (uuid.UUID('17d2bd00-57b7-4756-b14e-43bf1f102585'), 'Cleric'), (uuid.UUID('e72b02b5-a7d0-4b1b-860f-7c965ea5e18c'), 'Fighter'), (uuid.UUID('32ea43f0-8f6f-4ce4-829c-f58955a758d1'), 'Rogue'), (uuid.UUID('ef560074-395d-4e42-b5ac-5ad9d3342271'), 'Wizard')])),
                ('character_class_skill_choices', models.JSONField(default=list)),
                ('character_class_cantrip_choices', models.JSONField(blank=True, default=list)),
                ('character_class_spell_choices', models.JSONField(blank=True, default=list)),
                ('ability_points', models.JSONField(default=list)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('alignment', models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'), ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'), ('True Neutral', 'True Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'), ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'), ('Chaotic Evil', 'Chaotic Evil')], max_length=100)),
                ('background', models.TextField()),
                ('traits', models.JSONField(blank=True, default=list)),
                ('ideals', models.JSONField(blank=True, default=list)),
                ('bonds', models.JSONField(blank=True, default=list)),
                ('flaws', models.JSONField(blank=True, default=list)),
                ('height', models.CharField(max_length=100)),
                ('build', models.CharField(max_length=100)),
                ('skin_tone', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=100)),
                ('hair_style', models.CharField(max_length=100)),
                ('hair_length', models.CharField(choices=[('Bald', 'Bald'), ('Cropped', 'Cropped'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=100)),
                ('hair_type', models.CharField(choices=[('Straight', 'Straight'), ('Wavy', 'Wavy'), ('Curly', 'Curly'), ('Coily', 'Coily')], max_length=100)),
                ('facial_hair_style', models.CharField(choices=[('None', 'None'), ('Stubble', 'Stubble'), ('Full Beard', 'Full Beard'), ('Goatee', 'Goatee'), ('Moustache', 'Moustache'), ('Sideburns', 'Sideburns'), ('Soul Patch', 'Soul Patch'), ('Mutton Chops', 'Mutton Chops')], max_length=100)),
                ('facial_hair_length', models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('eye_shape', models.CharField(choices=[('Almond', 'Almond'), ('Round', 'Round'), ('Hooded', 'Hooded'), ('Monolid', 'Monolid'), ('Upturned', 'Upturned'), ('Downturned', 'Downturned')], max_length=100)),
                ('distinguishing_features', models.CharField(blank=True, max_length=300)),
                ('clothing_style', models.CharField(max_length=200)),
                ('clothing_colors', models.CharField(max_length=200)),
                ('clothing_accessories', models.CharField(blank=True, max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='fantasy-placeholder_tq6d9i', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('liked_by', models.ManyToManyField(related_name='liked_characters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
