# Generated by Django 5.1.5 on 2025-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
