# Generated by Django 5.1.5 on 2025-01-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bonds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class_cantrip_choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class_spell_choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing_accessories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='distinguishing_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='flaws',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='ideals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
