# Generated by Django 5.1.5 on 2025-01-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.CharField(default='/static/images/fantasy-placeholder.webp', max_length=200),
        ),
    ]
