# Generated by Django 5.1.5 on 2025-01-27 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_bonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
