# Generated by Django 5.1.5 on 2025-02-01 21:08

import characters.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'), ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'), ('True Neutral', 'True Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'), ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'), ('Chaotic Evil', 'Chaotic Evil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.UUIDField(choices=[(uuid.UUID('44f84547-8935-4ab4-bd29-fb60d0000d04'), 'Barbarian'), (uuid.UUID('ea6fbdc2-82c7-44d7-b065-bd70e136ccc7'), 'Bard'), (uuid.UUID('17d2bd00-57b7-4756-b14e-43bf1f102585'), 'Cleric'), (uuid.UUID('e72b02b5-a7d0-4b1b-860f-7c965ea5e18c'), 'Fighter'), (uuid.UUID('32ea43f0-8f6f-4ce4-829c-f58955a758d1'), 'Rogue'), (uuid.UUID('ef560074-395d-4e42-b5ac-5ad9d3342271'), 'Wizard')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='distinguishing_features',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye_shape',
            field=models.CharField(choices=[('Almond', 'Almond'), ('Round', 'Round'), ('Hooded', 'Hooded'), ('Monolid', 'Monolid'), ('Upturned', 'Upturned'), ('Downturned', 'Downturned')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='facial_hair_length',
            field=models.CharField(choices=[('None', 'None'), ('Stubble', 'Stubble'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='facial_hair_style',
            field=models.CharField(choices=[('None', 'None'), ('Stubble', 'Stubble'), ('Full Beard', 'Full Beard'), ('Goatee', 'Goatee'), ('Moustache', 'Moustache'), ('Sideburns', 'Sideburns'), ('Soul Patch', 'Soul Patch'), ('Mutton Chops', 'Mutton Chops')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_length',
            field=models.CharField(choices=[('Bald', 'Bald'), ('Cropped', 'Cropped'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_type',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Wavy', 'Wavy'), ('Curly', 'Curly'), ('Coily', 'Coily')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(default=characters.models.get_default_image_url),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.UUIDField(choices=[(uuid.UUID('095914ea-d0a5-41dd-a003-6b5d4558a3ad'), 'Dwarf'), (uuid.UUID('576c1e3a-8464-4c1a-bbe7-3dde6813bbd3'), 'Elf'), (uuid.UUID('bf3b0c49-80cc-4258-85a0-3974f656469a'), 'Halfling'), (uuid.UUID('4725316c-cfc5-44a2-a69f-563088dec352'), 'Human'), (uuid.UUID('ec1f0336-fb41-4ac8-b1f3-2a574ddb1bd5'), 'Half-Elf'), (uuid.UUID('8b5c75dd-3d4f-41b4-a7c2-ec516f02256e'), 'Tiefling')]),
        ),
    ]
