# Generated by Django 5.1.5 on 2025-02-06 16:27

import characters.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, default=characters.models.get_default_image_url, max_length=255, verbose_name='image'),
        ),
    ]
