# Generated by Django 5.1.5 on 2025-02-08 01:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options_alter_character_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='fantasy-placeholder_tq6d9i', max_length=255, verbose_name='image'),
        ),
    ]
