# Generated by Django 5.1.5 on 2025-02-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_created_at_alter_character_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clothing_accessories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing_colors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='facial_hair_length',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=100),
        ),
    ]
