# Generated by Django 5.1.5 on 2025-02-03 11:57

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(default=userprofile.models.get_default_image_url),
        ),
    ]
